name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Adjust the Ruby version as necessary

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the Jekyll site
      run: bundle exec jekyll build --future

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        publish_dir: ./_site
